try:
    from pipeline_consumers.constants import (
        KAFKA_BOOTSTRAP,
        REQUESTS_CLEAN_TOPIC,
        REQUESTS_FRAUD_TOPIC,
        REQUESTS_RAW_TOPIC,
        REQUESTS_SUS_TOPIC,
    )
except ImportError:
    KAFKA_BOOTSTRAP = "localhost:9092"
    REQUESTS_CLEAN_TOPIC = "requests.clean"
    REQUESTS_FRAUD_TOPIC = "requests.fraud"
    REQUESTS_RAW_TOPIC = "requests.raw"
    REQUESTS_SUS_TOPIC = "requests.sus"

REQUEST_RAW_TOPIC = REQUESTS_RAW_TOPIC

IP_FRAUD_THRESHOLD = 15
IP_WINDOW_BURST_THRESHOLD = 8
IP_WINDOW_BURST_SCORE = 0.3
IP_WINDOW_BURST_WINDOW_SECONDS = 60
PROMPT_SIMILARITY_THRESHOLD = 3
PROMPT_SIMILARITY_WINDOW_SECONDS = 60
PROMPT_SIMILARITY_SCORE = 0.3
REQUEST_WATERMARK_OUT_OF_ORDERNESS_SECONDS = 5
FRAUD_SCORE_SUSPICIOUS_THRESHOLD = 0.5
FRAUD_SCORE_HARD_THRESHOLD = 0.8
IP_STATE_TTL_MINUTES = 30
FRAUD_CONSUMER_GROUP = "flink-fraud-consumer"
FRAUD_JOB_NAME = "Flink Fraud Detection"
SESSION_WINDOW_GAP_SECONDS = 180

MAX_SESSION_FREQ = 30
MOBILE_IP_REPEAT_SECONDS = 3.0
DESKTOP_IP_REPEAT_SECONDS = 2.0
SUSPICIOUS_UA_PENALTY = 0.1
IP_REPEAT_PENALTY = 0.6
SESSION_BURST_PENALTY = 0.5
NEGATIVE_KEYWORD_PENALTY = 0.7
INVALID_UA_PENALTY = 0.2
LANGUAGE_MISMATCH_PENALTY = 0.2
