from pipeline_consumers.constants import (
    KAFKA_BOOTSTRAP,
    REQUESTS_CLEAN_TOPIC,
    REQUESTS_FRAUD_TOPIC,
    REQUESTS_RAW_TOPIC,
    REQUESTS_SUS_TOPIC,
)

FRAUD_CONSUMER_GROUP = "flink-fraud-consumer"
FRAUD_JOB_NAME = "Flink Fraud Starter"
REQUEST_WATERMARK_OUT_OF_ORDERNESS_SECONDS = 5

SUSPICIOUS_SCORE_THRESHOLD = 0.5
FRAUD_SCORE_THRESHOLD = 0.8

IP_BURST_WINDOW_SECONDS = 60
IP_BURST_MAX_REQUESTS = 8
IP_BURST_SCORE = 0.6

NEGATIVE_PROMPT_SCORE = 0.2
BAD_USER_AGENT_SCORE = 0.2
ASN_RISK_SCORE = 0.2
LANGUAGE_MISMATCH_COUNTRY_SCORE = 0.1

HIGH_RISK_ASNS = {
    9009,
    14061,
    16276,
    20473,
    24940,
}
