from pipeline_consumers.constants import (
    KAFKA_BOOTSTRAP,
    REQUESTS_CLEAN_TOPIC,
    REQUESTS_FRAUD_TOPIC,
    REQUESTS_RAW_TOPIC,
    REQUESTS_SUS_TOPIC,
)

FRAUD_CONSUMER_GROUP = "flink-fraud-consumer"
FRAUD_JOB_NAME = "Flink Fraud Starter"
REQUEST_WATERMARK_OUT_OF_ORDERNESS_SECONDS = 5

SUSPICIOUS_SCORE_THRESHOLD = 0.5
FRAUD_SCORE_THRESHOLD = 0.7

IP_BURST_WINDOW_SECONDS = 60
IP_BURST_MAX_REQUESTS = 8
IP_BURST_SCORE = 0.35

SESSION_BURST_WINDOW_SECONDS = 60
SESSION_BURST_MAX_REQUESTS = 12
SESSION_BURST_SCORE = 0.4

SESSION_IP_CHURN_WINDOW_SECONDS = 120
SESSION_IP_CHURN_MIN_UNIQUE_IPS = 2
SESSION_IP_CHURN_SCORE = 0.4

SESSION_COUNTRY_HOP_WINDOW_SECONDS = 120
SESSION_COUNTRY_HOP_MAX_COUNTRIES = 2
SESSION_COUNTRY_HOP_SCORE = 0.5

SESSION_ASN_CHURN_WINDOW_SECONDS = 120
SESSION_ASN_CHURN_MIN_UNIQUE_ASNS = 2
SESSION_ASN_CHURN_SCORE = 0.4

PROMPT_REPLAY_WINDOW_SECONDS = 300
PROMPT_REPLAY_MIN_SIMILARITY = 0.9
PROMPT_REPLAY_SCORE = 0.4

REGULAR_CADENCE_MIN_REQUESTS = 4
REGULAR_CADENCE_MAX_INTERVAL_DRIFT_MS = 250
REGULAR_CADENCE_SCORE = 0.3

NEGATIVE_PROMPT_SCORE = 0.15
BAD_USER_AGENT_SCORE = 0.3
ASN_RISK_SCORE = 0.2
GEO_LANGUAGE_MISMATCH_SCORE = 0.15
PUBLISHER_BURST_VOLUME_SCORE = 0.35

PUBLISHER_BURST_WINDOW_SECONDS = 300
PUBLISHER_BURST_MAX_REQUESTS = 200
PUBLISHER_BURST_SCORE = 0.5

PUBLISHER_RATE_WINDOW_SECONDS = 600
PUBLISHER_SUSPICIOUS_RATE_MIN_REQUESTS = 30
PUBLISHER_SUSPICIOUS_RATE_THRESHOLD = 0.10
PUBLISHER_SUSPICIOUS_RATE_SCORE = 0.15

PUBLISHER_BAD_UA_RATE_MIN_REQUESTS = 30
PUBLISHER_BAD_UA_RATE_THRESHOLD = 0.10
PUBLISHER_BAD_UA_RATE_SCORE = 0.3

# --- Publisher dispersion (compound rule: only fire when ALL conditions met) ---
PUBLISHER_DISPERSION_WINDOW_SECONDS = 1800
PUBLISHER_NEW_IP_SCORE = 0.05
PUBLISHER_NEW_SESSION_SCORE = 0.03
PUBLISHER_COMPOUND_FARM_RATIO = 0.80
PUBLISHER_COMPOUND_FARM_SCORE = 0.45

PUBLISHER_FLAGGED_EXCLUDE_REASONS = frozenset({"ip_burst"})

HIGH_RISK_ASNS = {
    9009,
    14061,
    16276,
    20473,
    24940,
}
