def build_identity_verdict(
    *,
    req_id,
    event_time,
    publisher_id,
    verdict,
    score,
    reasons,
    current_count,
    window_request_count,
    window_size_seconds,
    similar_prompt_count,
    prompt_similarity_window_seconds,
    normalized_prompt_hash,
    prompt_repeat_count,
    session_count,
    country_count,
    publisher_count,
    top_country,
    top_country_frequency,
    unique_country_count,
    inter_request_gap_seconds,
    avg_inter_request_gap_seconds,
    avg_requests_per_session,
    avg_fraud_score,
    rolling_fraud_intensity,
    rolling_suspicious_count,
    rolling_moderation_hits,
    ip_hash,
    user_ip,
    prompt,
    shallow_fraud_score,
    shallow_fraud_flags,
) -> dict:
    return {
        "req_id": req_id,
        "event_time": event_time,
        "publisher_id": publisher_id,
        "verdict": verdict,
        "fraud_score": score,
        "reasons": reasons,
        "count_from_ip": current_count,
        "window_request_count": window_request_count,
        "window_size_seconds": window_size_seconds,
        "window_slide_seconds": None,
        "similar_prompt_count": similar_prompt_count,
        "prompt_similarity_window_seconds": prompt_similarity_window_seconds,
        "normalized_prompt_hash": normalized_prompt_hash,
        "prompt_repeat_count": prompt_repeat_count,
        "session_request_count": session_count,
        "country_frequency": country_count,
        "publisher_request_count_for_identity": publisher_count,
        "country_top": top_country,
        "country_top_frequency": top_country_frequency,
        "unique_country_count_recent": unique_country_count,
        "inter_request_gap_seconds": inter_request_gap_seconds,
        "avg_inter_request_gap_seconds": None
        if avg_inter_request_gap_seconds is None
        else round(float(avg_inter_request_gap_seconds), 3),
        "avg_requests_per_session": None
        if avg_requests_per_session is None
        else round(float(avg_requests_per_session), 3),
        "avg_fraud_score_recent": None if avg_fraud_score is None else round(float(avg_fraud_score), 3),
        "rolling_fraud_intensity": round(float(rolling_fraud_intensity), 3),
        "rolling_suspicious_count": int(rolling_suspicious_count),
        "rolling_moderation_hits": int(rolling_moderation_hits),
        "ip_hash": ip_hash,
        "user_ip": user_ip,
        "prompt_preview": prompt[:80],
        "shallow_fraud_score": shallow_fraud_score,
        "shallow_fraud_flags": shallow_fraud_flags,
        "cancel_downstream": verdict == "fraud",
    }
