LANGUAGE_COUNTRIES = {
    "arabic": {
        "AE",
        "BH",
        "DZ",
        "EG",
        "IQ",
        "JO",
        "KW",
        "LB",
        "LY",
        "MA",
        "OM",
        "QA",
        "SA",
        "SD",
        "SY",
        "TN",
        "YE",
    },
    "chinese": {"CN", "HK", "MO", "SG", "TW"},
    "czech": {"CZ"},
    "danish": {"DK"},
    "dutch": {"BE", "NL", "SR"},
    "finnish": {"FI"},
    "french": {"BE", "CA", "CH", "FR", "LU", "MC", "SN", "CI", "CM", "MA", "DZ", "TN"},
    "german": {"AT", "CH", "DE", "LI", "LU"},
    "greek": {"CY", "GR"},
    "hebrew": {"IL"},
    "hindi": {"IN"},
    "hungarian": {"HU"},
    "indonesian": {"ID"},
    "italian": {"CH", "IT", "SM", "VA"},
    "japanese": {"JP"},
    "korean": {"KR"},
    "malay": {"BN", "MY", "SG"},
    "norwegian": {"NO"},
    "polish": {"PL"},
    "portuguese": {"AO", "BR", "CV", "GW", "MZ", "PT", "ST", "TL"},
    "romanian": {"MD", "RO"},
    "russian": {"BY", "KG", "KZ", "RU"},
    "spanish": {
        "AR",
        "BO",
        "CL",
        "CO",
        "CR",
        "CU",
        "DO",
        "EC",
        "ES",
        "GQ",
        "GT",
        "HN",
        "MX",
        "NI",
        "PA",
        "PE",
        "PR",
        "PY",
        "SV",
        "UY",
        "VE",
    },
    "swedish": {"FI", "SE"},
    "thai": {"TH"},
    "turkish": {"CY", "TR"},
    "ukrainian": {"UA"},
    "vietnamese": {"VN"},
}

LANGUAGE_ALIASES = {
    "en": "english",
    "eng": "english",
    "es": "spanish",
    "spa": "spanish",
    "fr": "french",
    "de": "german",
    "it": "italian",
    "pt": "portuguese",
    "ru": "russian",
    "ja": "japanese",
    "jp": "japanese",
    "ko": "korean",
    "zh": "chinese",
    "ar": "arabic",
    "hi": "hindi",
    "tr": "turkish",
    "nl": "dutch",
    "pl": "polish",
    "uk": "ukrainian",
    "sv": "swedish",
    "no": "norwegian",
    "da": "danish",
    "fi": "finnish",
    "el": "greek",
    "ro": "romanian",
    "hu": "hungarian",
    "he": "hebrew",
    "th": "thai",
    "vi": "vietnamese",
    "id": "indonesian",
    "ms": "malay",
    "cs": "czech",
}
